services:
  devsecops-web:
    build:
      context: .
      dockerfile: Dockerfile.stg
    container_name: devsecops-frontend
    ports:
      - "3001:3001"
    environment:
      - VITE_API_URL=http://devsecops-backend:3000
    depends_on:
      - devsecops-backend
    networks:
      - devsecops_network

  devsecops-backend:
    build:
      context: ./devsecops-backend
    container_name: devsecops-backend
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=Amosjuang007!
      - DB_NAME=devsecop
      - DB_HOST=devsecops-db
      - DB_PORT=5432
    ports:
      - "3000:3000"
    depends_on:
      - devsecops-db
    networks:
      - devsecops_network
    command: ["npm", "start"] # Ensure this starts the backend server

  devsecops-db:
    image: postgres:14
    container_name: devsecops-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Amosjuang007!
      POSTGRES_DB: devsecops
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=50'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - devsecops_network

  backend-migrate:
    build:
      context: ./devsecops-backend
    environment:
      DB_USER: postgres
      DB_HOST: devsecops-db
      DB_NAME: devsecop
      DB_PASSWORD: Amosjuang007!
      DB_PORT: 5432
    depends_on:
      - devsecops-db
    networks:
      - devsecops_network

volumes:
  db_data:

networks:
  devsecops_network:
    name: devsecops_network  
    driver: bridge